### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-fighterfish#13]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Created https://jenkins.eclipse.org/glassfish/job/fighterfish-module-master-build/ job.
It does maven clean install for OSGI modules mentioned in the release jobs.
