### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-fighterfish#14]
This task is for creating a project release CI/CD pipeline. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by jayasheelankumar** [comment]
Created the jobs for all the artifacts in figtherfish.

**Comment by Tomas-Kraus** [comment]
Those jobs are not working - I see
```
gpg: signing failed: Not a tty
gpg: signing failed: Not a tty

```
in console output. This is caused by old parent pom. Made PR to update pareent to 1.0.2
https://github.com/eclipse-ee4j/glassfish-fighterfish/pull/18
https://github.com/eclipse-ee4j/glassfish-fighterfish/pull/19

**Comment by Tomas-Kraus** [comment]
Well, looks like you have to release modules parent first and update versions to make rest of the jobs working too. Another option is to do everything in a single job where parent is installed and all modules are updated to this new parent. But I have no idea how release process should work properly in this project.

**Comment by romain-grecourt** [comment]
Sahoo did things that way but he was releasing modules individually from command line.
IMO you should refactor the pom files and make it a single reactor that you can release in one shot.

**Comment by Tomas-Kraus** [comment]
Yes, it's another option to go. But there is one more thing - versioning.
If you check https://github.com/javaee/fighterfish/releases, we have versions from 1.0.1 up to 2.0.1 for various modules.
Single reactor solution would mean releasing everything with a single shot and if possible, with the same version numbers.
I'm even not commiter here so I won't do such a change without others agreement.
