### ISSUE TITLE
osgi-web-container version 2.0.2 is not compatible with jakarta.faces (mojarra) 2.3.9 As shipped in Glassfish 5.1.0

### ISSUE THREAD

**Issue by pjs102** [eclipse-ee4j/glassfish-fighterfish#29]
As outlined in https://github.com/eclipse-ee4j/glassfish/issues/22603 there is an incompatibility between the osgi-web-container and the version of mojarra that is shipped in glassfish 5.1.0.  This results in a java.lang.NoSuchFieldError being thrown.

As part of the Glassfish 5.1.0 release, the maven coordinates were updated for the jsf-api and jfs-impl, these are now jakarta.faces:jakarta.faces-api and org.glassfish:jakarta.faces.  Please update the module/parent pom file and fix the subsequent errors in osgi-web-container.

Thanks
Paul

**Comment by romain-grecourt** [comment]
This is fixed in master. The next version to be released is 3.0.0.
